services:
  laravel-app-api:
    build:
      context: .
      dockerfile: docker/dev/php/php.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/laravel-api/src:/var/www/html
    command: >
     sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"

    
    networks:
      - proxy_network

  nginx:
    image: nginx:latest
    ports:
      - "83:80"
    volumes:
      - /home/abdallah644/projects/my-projects/laravel-api/src:/var/www/html
      - /home/abdallah644/projects/my-projects/laravel-api/docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_network

  # reverb:
  #   build:
  #     context: .
  #     dockerfile: docker/dev/php/php.dockerfile
  #   working_dir: /var/www/html
  #   command: php artisan reverb:start --host=0.0.0.0 --port=8080
  #   volumes:
  #     - /home/abdallah644/projects/my-projects/laravel-api/src:/var/www/html
  #   env_file:
  #     - ./src/.env
  #   depends_on:
  #     - laravel-app-api
  #   networks:
  #     - proxy_network
  #   ports:
  #     - "8081:8080" 
 
  artisan:
    build:
      context: /home/abdallah644/projects/my-projects/laravel-api/src
      dockerfile: /home/abdallah644/projects/my-projects/laravel-api/docker/dev/artisan/artisan.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/laravel-api/src:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - laravel-app-api

  composer:
    image: composer:latest
    container_name: composer_api
    volumes:
      - /home/abdallah644/projects/my-projects/laravel-api/src:/app
    working_dir: /app
    command: install
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true

volumes:
  mssql_data:
